[package]
name = "Maze_22_5_2026"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.1.1"
rand= "0.8"

[[bin]]
name = "Maze_22_5_2026"
path = "main.rs"


[[bin]]
name = "maze_lento_y_extranio"
path = "maze_lento_y_extranio.rs"

[[bin]]
name = "ref"
path = "ref.rs"

[[bin]]
name= "maze_con_colores"
path = "maze_con_colores.rs"

[[bin]]
name = "p3"
path = "p3.rs"

[[bin]]
name = "p4"
path = "p4.rs"

[[bin]]
name = "main"
path = "main.rs"
